export {default as Login} from './component/Login'
export {default as Register} from './component/Register'
export {default as DetailRegister} from './component/DetailRegister'
export {default as UserInfo} from './component/UserInfo'
export {default as UserService} from './service/UserService'